name: atendence_hcs
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  http: ^1.1.0
  intl: ^0.18.1
  community_material_icon: ^5.9.55
  shared_preferences: ^2.2.2
  pdf: ^3.10.7
  path_provider: ^2.1.2
  open_file: ^3.3.2
  flutter_launcher_icons: ^0.13.1
  fluttertoast: ^8.2.4
  # for auth biomatriks
  local_auth: ^2.1.8
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/iconApp.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icon/
    - assets/pdf/pdftest.pdf
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
